import { MainContentProps } from "@/types/docs";
import {
  createListBlock,
  createContentBlock,
  createLabelBlock,
  createCalloutBlock
} from "@/constants/docs";

export const WEB_WORKFLOW_CONTENT: MainContentProps = {
  title: "Web Workflow",
  description: "Manage your entire software delivery pipeline from the intuitive Revolte Dashboard.",
  sections: [
    {
      id: "navigation",
      title: "UI Navigation",
      blocks: [
        createContentBlock("The Revolte Dashboard provides a high-level overview of your workspace, deployments, and build history. Access it at console.revolte.io."),
        createListBlock("list", [
          "**Build Center:** The central hub for submitting requirements and monitoring implementation progress.",
          "**Deployment Pipeline:** View live environments and manage rollouts across preview and production stages.",
          "**Observability Hub:** Real-time access to logs, metrics, and system health status."
        ])
      ]
    },
    {
      id: "key-actions",
      title: "Key Actions",
      blocks: [
        createLabelBlock("Trigger a build"),
        createContentBlock("Enter your requirement in the input field within the Build Center. Revolte instantly analyzes the context and begins the generation process."),
        createLabelBlock("Approve PRs"),
        createContentBlock("Review the artifacts generated by Revolte directly within the web interface or via the connected source control provider."),
        createLabelBlock("Manage Environments"),
        createContentBlock("Switch between Preview and Production environments to validate features before final release.")
      ]
    },
    {
      id: "automation-flow",
      title: "Automated Flow",
      blocks: [
        createContentBlock("Every action triggered in the Web UI orchestrates a series of background automations: cloud resource provisioning, CI/CD pipeline triggering, and automated testing are all managed by the platform invisibly.")
      ]
    }
  ]
};
